<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */


?>
<div id="cart-totals" class="cart-totals" data-bind="scope:'block-totals'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <?php
       $blockObj= $block->getLayout()->createBlock('Ambab\EMImodule\Block\Catalog\Product\View');
       $orderTotal = $blockObj->getSubtotal(); 
       $adminAmt = $blockObj->minimumAmt();
        $finalAmt= $adminAmt - $orderTotal;  
        ?>
        <?php
        if($adminAmt > $orderTotal)
        { ?>
            <h3 style="color:red;">Add more $ <?php echo $finalAmt?> to proceed</h3>
            <!-- echo "Add more $".$finalAmt." to process"; -->
       <?php } ?>
    
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
                }
            }
    </script>
</div>
